blog/urls.py
from django.urls import path
from .views import ArticleCreateView, BlogListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView
from django.views.decorators.cache import cache_page


urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('', cache_page(60*60)(BlogListView.as_view()), name='list'),
    path('read/<slug:slug>/', ArticleDetailView.as_view(), name='view'),
    path('edit/<slug:slug>/', ArticleUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', ArticleDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from main.views import page_not_found

urlpatterns = (([
                    path('admin/', admin.site.urls),
                    path('', include('main.urls')),
                    path('blog/', include('blog.urls')),
                    path('users/', include('users.urls')),
                ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
               + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

handler404 = page_not_found

# admin.site.site_header = 'Admin Panel'
# admin.site.index_title = 'MailMate'

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Article(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'draft', 'Draft'
        PUBLISHED = 'published', 'Published'

    title = models.CharField(max_length=100, verbose_name='Title')
    slug = models.CharField(max_length=100, unique=True, db_index=True)
    content = models.TextField(blank=True, null=True, db_index=True)
    image = models.ImageField(upload_to='images/blog/', blank=True, null=True, verbose_name='Image Path')
    time_created = models.DateTimeField(auto_now_add=True)
    publication = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.PUBLISHED,
    )
    views_count = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Checks if there is an image
        if self.image:
            # Deletes image
            self.image.delete()
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'article'
        verbose_name_plural = 'articles'

    def get_absolute_url(self):
        return reverse('view', kwargs={'slug': self.slug})

blog/views.py
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin
from blog.models import Article


class BlogListView(ListView):
    # Displays a list of published articles
    model = Article
    template_name = 'blog/blog.html'
    context_object_name = 'articles'
    paginate_by = 6
    extra_context = {'page_title': 'Mailing Blog', 'title': 'Mailing Blog'}

    # Only retrieves published articles for the view
    def get_queryset(self, *args, **kwargs):
        return Article.objects.filter(publication=Article.Status.PUBLISHED).order_by('id')

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['articles'] = context['object_list']
        return context


class ArticleDetailView(DetailView):
    # Shows the details of a single article
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page_title = 'Mailing Blog: read'
        context['page_title'] = page_title
        context['title'] = self.object.title
        return context

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)  # Retrieves the article
        self.object.views_count += 1  # Increment the views count
        self.object.save(update_fields=['views_count'])   # Saves only views_count field
        return self.object


class ArticleFormMixin:
    # Validates the form and sets the article's slug
    def form_valid(self, form):
        if form.is_valid():
            article = form.save(commit=False)
            article.slug = slugify(article.title)

            image = form.cleaned_data['image']
            if image:
                article.image = image
            article.save()
            return super().form_valid(form)


class ArticleCreateView(UserPassesTestMixin, ArticleFormMixin, CreateView):
    model = Article
    fields = ('title', 'content', 'publication', 'image')
    extra_context = {'page_title': 'Mailing Blog: write', 'title': 'Writing New Post'}

    def test_func(self):
        # User must be in 'content-manager' group
        return self.request.user.groups.filter(name='content-manager').exists()


class ArticleUpdateView(UserPassesTestMixin, ArticleFormMixin, UpdateView):
    # User must pass certain checks to update an article
    model = Article
    fields = ('title', 'content', 'publication', 'image')
    extra_context = {'page_title': 'Mailing Blog: edit', 'title': 'Updating the Post'}

    # Checks if the user is allowed to update the article
    def test_func(self):
        article = self.get_object()
        # User must be in 'content-manager' group
        return self.request.user.groups.filter(name='content-manager').exists()


class ArticleDeleteView(UserPassesTestMixin, DeleteView):
    model = Article
    template_name = 'blog/article_delete.html'
    extra_context = {'page_title': 'Mailing Blog', 'title': 'Delete the Post'}
    success_url = reverse_lazy('list')

    def test_func(self):
        article = self.get_object()
        # User must be in 'content-manager' group
        return self.request.user.groups.filter(name='content-manager').exists()

blog/templates/blog/article_delete.html
<!DOCTYPE html>
{% extends 'base.html' %}

{% block content %}
{% include 'includes/background_strip.html' %}

<div class="d-flex justify-content-center align-items-center" style="height: 30vh;">
    <div class="col-3">
        <div class="card">
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p class="text-align-justify">Delete the article {{article.title}}?</p>
                    <div class="d-flex m-4">
                        <button type="submit" class="btn btn-danger" style="margin-right: 15px;">Confirm</button>
                        <a href="{% url 'list' %}" class="btn btn-warning">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% include 'includes/Lower_border.html' %}
{% endblock %}

blog/templates/blog/article_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load blog_tags %}

{% block content %}
{% include 'includes/background_strip.html' %}

<section style="overflow-y: auto;">
    <div class="container d-flex flex-wrap">
        <div class="card mx-auto col-md-8 w-100 h-100 border-0" style="margin-top: 30px;">
            <div class="row g-0 d-flex justify-content-center">
                <div class="col-md-4 mb-5 mt-4 mr-4">
                    <img src="{% imagepath_tag article.image %}"
                         class="img-fluid rounded-start" alt="Post Image" style="max-width: 120%; height: auto;">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text" style="text-align: justify; width: 100%;">{{ article.content|linebreaks }}</p>
                        <p style="text-align: right;"><b>Published:</b> {{ article.time_created|date:"F j, Y" }}</p>
                        <li style="text-align: left;">Pageviews: {{ object.views_count }}</li>
                        <li style="text-align: left;"><a href="{% url 'list' %}">To all articles</a></li>
                        <br>

                        <!-- Buttons for editing, deleting, viewing articles -->
                        {% if perms.blog.change_article %}
                    <p style="text-align: left;"><a href="{% url 'update' slug=article.slug %}">Edit</a> |
                    <a href="{% url 'delete' slug=article.slug %}">Delete</a></p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% include 'includes/Lower_border.html' %}
{% endblock %}

blog/templates/blog/article_form.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'includes/background_strip.html' %}

<div class="container mt-4">
    <div class="row justify-content-left">
        <div class="col-6 mb-4" style="margin-left: 1rem;">
            <div class="card" style="margin-bottom: 60px;">
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                            Save
                            {% else %}
                            Create
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
        <br><br>
        <div class="col-md-5">
            <img src="{% static 'blog/images/article.jpg' %}" class="img-fluid" alt="Article Image"
                 style="max-width: 80%; height: auto; margin-top: 40px; margin-left: 60px;">
        </div>
    </div>
</div>

{% include 'includes/Lower_border.html' %}
{% endblock %}

blog/templates/blog/blog.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load blog_tags %}

{% block content %}
{% include 'includes/background_strip.html' %}

<div class="container mt-4">
    <div class="row">
        {% for article in articles %}
        <div class="col-md-4 mb-4">
            <a href="{% url 'view' article.slug %}">
            <img src="{% imagepath_tag article.image %}" class="card-img-top" alt="Post Image">
                </a>
            <div class="card-body">
                <h5 class="card-title">{{ article.title }}</h5>
                <br>
                <p class="card-text">{{ article.content|linebreaks|truncatewords:40 }}</p>
                <a href="{% url 'view' article.slug %}" class="btn btn-outline-success btn-sm">Read</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% if page_obj.has_other_pages %}
{% include 'includes/pagination.html' %}
{% endif %}

{% include 'includes/Lower_border.html' %}
{% endblock %}