blog/urls.py
from django.urls import path
from .views import ArticleCreateView, BlogListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView
from django.views.decorators.cache import cache_page


urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('', cache_page(60*60)(BlogListView.as_view()), name='list'),
    path('read/<slug:slug>/', ArticleDetailView.as_view(), name='view'),
    path('edit/<slug:slug>/', ArticleUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', ArticleDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from main.views import page_not_found

urlpatterns = (([
                    path('admin/', admin.site.urls),
                    path('', include('main.urls')),
                    path('blog/', include('blog.urls')),
                    path('users/', include('users.urls')),
                ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
               + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

handler404 = page_not_found

# admin.site.site_header = 'Admin Panel'
# admin.site.index_title = 'MailMate'

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from .views import LoginUser, RegisterUser, ProfileUser, UserPasswordChange, activation_sent_view, activate_account, \
    user_list

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # for changing password
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name='password_change_done'),

    # for generating a link to reset password
    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

    path('register/', RegisterUser.as_view(), name='register'),
    path('activation-sent/', activation_sent_view, name='activation_sent'),
    path('activate/<str:activation_token>/', activate_account, name='activate'),
    path('profile/', ProfileUser.as_view(), name='profile'),

    path('', user_list, name='user_list'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """
      Custom User model that extends Django's built-in AbstractUser model.

      This model adds additional fields like email, activation_token.
      It also changes the default username field to an email field.
      """
    email = models.EmailField(unique=True, verbose_name='Email')
    username = models.CharField(max_length=50, blank=True, null=True, default='ghost', verbose_name="Username")
    activation_token = models.CharField(max_length=100, blank=True, null=True)
    avatar = models.ImageField(upload_to="images/users/", blank=True, null=True, verbose_name="Image")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def is_manager(self):
        return self.groups.filter(name='content-manager').exists()

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm
from django.core.mail import send_mail
from django.urls import reverse
from django.utils.crypto import get_random_string
from django.utils.html import format_html


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Username or Email: ', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Password: ', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ('email', 'password')


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label="Username: ", required=False, widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label="*Password: ", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label="*Confirm password: ", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'password1', 'password2']
        labels = {
            'email': '*E-mail: ',
            'first_name': 'First name: ',
            'last_name': 'Last name: ',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        """
        Checks that the email is unique.
        If the email already exists in the database, it raises a ValidationError.
        """
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("This email already exists.")
        return email

    def save(self, commit=True):
        """
        Saves the form data to a User object and generates an activation token.
        It calls the superclass save method to save the form data to a User object,
        but it doesn't save the User object to the database yet.
        It generates a random string for the activation token and saves it to the User object.
        Finally, it saves the User object to the database and returns the User object.
        """
        user = super().save(commit=False)
        user.activation_token = get_random_string(length=32)
        user.save()
        return user


class SimpleRegisterUserForm(RegisterUserForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].required = False
        del self.fields['first_name']
        del self.fields['last_name']

    def clean_email(self):
        """
        Checks that the email is unique.
        If the email already exists in the database, it raises a ValidationError.
        """
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("This email already exists.")
        return email


class ProfileUserForm(forms.ModelForm):
    email = forms.CharField(disabled=True, label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name', 'avatar']
        labels = {
            'first_name': 'First name',
            'last_name': 'Last name',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-input'}),
            'last_name': forms.TextInput(attrs={'class': 'form-input'}),
        }


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Old password", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="New password", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Confirm password",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))


class CustomPasswordResetForm(PasswordResetForm):
    # Generates new temporary password
    def save(self, domain_override=None,
             subject_template_name=None,
             email_template_name=None,
             use_https=False, token_generator=None,
             from_email=None, request=None, extra_email_context=None,
             subject=None, message=None, html_email_template_name=None, **kwargs):

        email = self.cleaned_data["email"]
        user_model = get_user_model()
        try:
            user = user_model._default_manager.get(email=email)
        except user_model.DoesNotExist:
            # Handles the case when the user is not found
            return

        # Generates temporary password
        temp_password = get_random_string(length=12)
        user.set_password(temp_password)
        user.save()

        # Defines the URL for login page
        login_url = reverse('users:login')
        full_login_url = '{}://{}{}'.format('https' if use_https else 'http', domain_override or request.get_host(),
                                            login_url)

        # Sends letter with a temporary password
        subject = 'Your temporary password'
        message = format_html(
            "You're receiving this email because you requested a password reset for your user account at Mail Mate.<br><br>"
            "Your temporary password: {}.<br>"
            "Please use it to login and go to your profile to set your new password.<br><br>"
            "<a href='{}'>Login to Mail Mate</a>",
            temp_password,
            full_login_url
        )
        send_mail(subject, message, from_email, [email], fail_silently=False, html_message=message)

        # Returns None, since Django's tokenization mechanism to reset the password isn't used
        return

users/views.py
from django.conf import settings
from django.contrib.auth import login, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView
from users.forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm, \
    CustomPasswordResetForm
from users.services import activate_user, send_activation_email


class LoginUser(LoginView):
    """
       View for logging in users.

       It uses the LoginUserForm for validation and renders the 'users/login.html' template.
       After successful login, it redirects the user to the home page.
       """
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': 'Authorization',
                     'page_title': 'Login'}


class RegisterUser(CreateView):
    """
       View for registering new users.

       It uses the RegisterUserForm for validation and renders the 'users/register.html' template.
       After successful registration, it sends an email to the user with an activation link.
       The user is then redirected to the activation sent page.
       """
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': 'Registration', 'page_title': 'Sign up'}
    success_url = reverse_lazy('users:activation_sent')  # for verifying

    def form_valid(self, form):
        response = super().form_valid(form)
        new_user = form.instance  # Gets user object from a form without saving

        # Sends an email to the user with the activation link
        send_activation_email(self.request, new_user)  # service function is used
        return response


class ProfileUser(LoginRequiredMixin, UpdateView):
    """
       View for updating user profiles.

       It uses the ProfileUserForm for validation and renders the 'users/profile.html' template.
       Only logged in users can access this view.
       After successful update, it redirects the user to the home page.
       """
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {
        'title': 'Profile',
        'page_title': 'Profile',
        'default_image': settings.DEFAULT_USER_IMAGE,
    }

    def get_success_url(self):
        return reverse_lazy('home')

    def get_object(self, queryset=None):
        # Returns the current logged in user
        return self.request.user


class UserPasswordChange(PasswordChangeView):
    """
      View for changing the user's password.

      It uses the UserPasswordChangeForm for validation and renders the 'users/password_change_form.html' template.
      After successful password change, it redirects the user to the 'password_change_done' page.
      """
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {'title': 'Change password', 'page_title': 'Change password'}


def activation_sent_view(request):
    """Function-based view for rendering the 'users/activation_sent.html' template."""
    return render(request, 'users/activation_sent.html')


def activate_account(request, activation_token):
    """
      Function to activate a user's account.

      It finds the user with the given activation token, marks the user as active,
      removes the activation token, logs the user in, and redirects the user to the profile page.
      """
    user = activate_user(activation_token)  # service function is used
    login(request, user, backend='django.contrib.auth.backends.ModelBackend')
    return redirect(reverse_lazy('users:profile'))


class CustomPasswordResetView(PasswordResetView):
    """
     View for resetting the user's password.

     It uses the CustomPasswordResetForm for validation and renders the 'users/password_reset_form.html' template.
     After successful password reset, it redirects the user to the 'password_reset_done' page.
     """
    form_class = CustomPasswordResetForm
    template_name = 'users/password_reset_form.html'
    email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')


def is_content_manager_or_admin(user):
    return user.is_superuser or user.is_manager()


@login_required
@user_passes_test(is_content_manager_or_admin)
def user_list(request):
    if request.method == 'POST':
        blocked_users_ids = request.POST.getlist('blocked_users')
        blocked_users = get_user_model().objects.filter(id__in=blocked_users_ids)
        unblocked_users_ids = request.POST.getlist('unblocked_users')
        unblocked_users = get_user_model().objects.filter(id__in=unblocked_users_ids)

        for user in blocked_users:
            user.is_active = False
            user.save()

        for user in unblocked_users:
            user.is_active = True
            user.save()

        return redirect('users:user_list')

    users = get_user_model().objects.all().order_by('pk')
    context = {
        'title': 'Users List',
        'page_title': 'Users',
        'users': users,
    }
    return render(request, 'users/user_list.html', context)

users/templates/users/activation_sent.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% include 'includes/background_strip.html' %}

    <section class="container-xxl mt-5">
        <div class="row">
            <!-- Image column -->
            <div class="col-md-6">
                <img src="{% static 'activation.jpg' %}" alt="Activation email"  class="img-fluid w-75">
            </div>
            <!-- Text column -->
            <div class="col-md-5">
                <h1 class="text-center text-black">Activation Email Sent!</h1>
                <br>
                <p>Thank you for registering! We have sent you an email with instructions to activate your account.</p>
                <p>Please check your inbox and follow the link provided to complete the registration process.</p>
            </div>

        </div>
    </section>

{% endblock %}

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'includes/background_strip.html' %}


<div class="container">
    <div class="row justify-content-center align-items-center" style="height: 60vh;">
        <!-- Form column -->
        <div class="col-10 col-md-4">
            <div class="card box-shadow">
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{{ next }}"/>
                        <div class="form-error mb-3">{{ form.non_field_errors }}</div>
                        {% for f in form %}
                        <div class="mb-3">
                            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                            {{ f }}
                            <div class="form-error">{{ f.errors }}</div>
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-warning w-50 mb-3">Login</button>

                        <p><a href="{% url 'users:password_reset' %}">Forgot password?</a></p>
                    </form>
                </div>
            </div>
        </div>
        <!-- Image column -->
        <div class="col-10 col-md-6">
            <img src="{% static 'login.jpg' %}" alt="Authorization" class="img-fluid w-75">
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_change_done.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% include 'includes/background_strip.html' %}

<div class="container">
    <div class="row justify-content-center align-items-center" style="height: 60vh;">
        <!-- Image column -->
        <div class="col-10 col-md-4 order-md-2">
            <img src="{% static 'success.jpg' %}" alt="Change-password" class="img-fluid w-60">
        </div>
        <!-- Text column -->
        <div class="col-10 col-md-4 order-md-1">
            <p>Password changed!</p>
            <p>You have successfully changed your password.
            <p><a href="{% url 'users:profile' %}">Return to
                profile</a>.</p>
            </p>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/password_change_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'includes/background_strip.html' %}

<div class="container">
    <div class="row justify-content-center align-items-center" style="height: 60vh;">
        <div class="col-12 col-md-4">
            <div class="card box-shadow">
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="form-error mb-3">{{ form.non_field_errors }}</div>
                        {% for f in form %}
                        <div class="mb-3">
                            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                            {{ f }}
                            <div class="form-error">{{ f.errors }}</div>
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-warning w-50">Change password</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- Image column -->
        <div class="col-10 col-md-4">
            <img src="{% static 'security.jpg' %}" alt="Change-password" class="img-fluid w-60">
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<section class="background-section">
    <div class="container-xxl">
        <div class="col-12">
            <h1 class="text-center text-black">Password changed!</h1>
            <p>You have successfully changed your password. Use it to <a href="{% url 'users:login' %}">login</a>.</p>
        </div>
    </div>
</section>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'includes/background_strip.html' %}

<div class="container">
    <div class="row justify-content-center align-items-center" style="height: 40vh;">
        <div class="col-10 col-md-4">
            <div class="card box-shadow">
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        {% for f in form %}
                        <div class="mb-3">
                            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                            {{ f }}
                            <div class="form-error">{{ f.errors }}</div>
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-warning w-50">Save</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- Image column -->
            <div class="col-md-5">
                <img src="{% static 'security.jpg' %}" alt="Security"  class="img-fluid w-75">
            </div>
    </div>
</div>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
{% include 'includes/background_strip.html' %}

<section class="container-xxl mt-5">
    <div class="row">
        <!-- Image column -->
        <div class="col-md-5">
            <img src="{% static 'activation.jpg' %}" alt="Activation email" class="img-fluid w-75">
        </div>
        <!-- Text column -->
        <div class="col-md-5">
            <br>
            <p>We’ve emailed you instructions for setting your password, if an account exists with the email you
                entered. You should receive them shortly.</p>
            <p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and
                check your spam folder.</p>
        </div>

    </div>
</section>

{% endblock %}

users/templates/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

users/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'includes/background_strip.html' %}

<div class="container">
    <div class="row justify-content-center align-items-center" style="height: 40vh;">
        <div class="col-10 col-md-4">
            <div class="card box-shadow">
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        {% for f in form %}
                        <div class="mb-3">
                            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                            {{ f }}
                            <div class="form-error">{{ f.errors }}</div>
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-warning w-50">Reset by email</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- Image column -->
        <div class="col-12 col-md-6">
            <img src="{% static 'email.jpg' %}" alt="Authorisation" class="img-fluid w-75">
        </div>
    </div>
</div>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'includes/background_strip.html' %}

<div class="container">
    <div class="row justify-content-center align-items-center" style="height: 90vh;">
        <!-- Image column -->
        <div class="col-10 col-md-6">
            <img src="{% static 'profile.jpg' %}" alt="Profile" class="img-fluid w-75">
        </div>
        <div class="col-10 col-md-4">
            <div class="card box-shadow">
                <div class="card-body">
                    <form method="post" action="" class="form-floating" enctype="multipart/form-data">
                        {% csrf_token %}

                        {% if user.avatar %}
                        <p style="text-align: center;">
                            <img src="{{ user.avatar.url }}" alt="User Avatar"
                                 style="max-width: 90%; max-height: 200px;"></p>
                        {% else %}
                        <p style="text-align: center;">
                            <img src="{{ default_image }}" alt="Default Image"
                                 style="max-width: 50%; max-height: 200px;"></p>
                        {% endif %}

                        <div class="form-error mb-3">{{ form.non_field_errors }}</div>
                        {% for f in form %}
                        <div class="mb-3">
                            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                            {{ f }}
                            <div class="form-error">{{ f.errors }}</div>
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-warning w-50">Save</button>
                    </form>
                </div>
            </div>
            <div class="d-flex justify-content-center">
            <p><a href="{% url 'users:password_change' %}">Change password</a></p>
        </div>
        </div>
    </div>
</div>
<br><br>

{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'includes/background_strip.html' %}

<div class="container">
    <div class="row justify-content-center align-items-center" style="height: 80vh;">
        <div class="col-12 col-md-4">
            <div class="card box-shadow">
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}

                        <div class="form-error mb-3">{{ form.non_field_errors }}</div>
                        {% for f in form %}
                        <div class="mb-3">
                            <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                            {{ f }}
                            <div class="form-error">{{ f.errors }}</div>
                        </div>
                        {% endfor %}
                        <button type="submit" class="btn btn-warning w-50 mb-3">Sign up</button>
                        <p>*Required fields</p>
                    </form>
                </div>
            </div>
        </div>
        <!-- Image column -->
        <div class="col-10 col-md-6">
            <img src="{% static 'registration.jpg' %}" alt="Registration" class="img-fluid w-75">
        </div>
    </div>
</div>
<br>

{% endblock %}

users/templates/users/user_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% include 'includes/background_strip.html' %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6 mt-5">
            <h5 class="text-center"><b>Select one or several users</b></h5>
            <br>
            <form method="post">
                {% csrf_token %}
                <table class="table table-borderless table-hover">
                    {% for user in users %}
                    <tr>
                        <td><b>{{ user.username }}</b></td>
                        <td><input type="checkbox" name="blocked_users" value="{{ user.id }}"></td>
                        <td><input type="checkbox" name="unblocked_users" value="{{ user.id }}"></td>
                        {% if not user.is_active %}
                        <td><span class="badge bg-danger">Blocked</span></td>
                        {% else %}
                        <td></td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                    <tr>
                        <td colspan="3" class="text-end">
                            <button type="submit" class="btn btn-outline-danger">Block Selected Users</button>
                            <button type="submit" class="btn btn-outline-success">Unblock Selected Users</button>
                        </td>
                    </tr>
                </table>
            </form>
        </div>
        <!-- Image column -->
        <div class="col-12 col-md-5">
            <img src="{% static 'block.jpg' %}" alt="Block" class="img-fluid w-75">
        </div>
    </div>
</div>
{% include 'includes/lower_border.html' %}
{% endblock %}