blog/urls.py
from django.urls import path
from .views import ArticleCreateView, BlogListView, ArticleDetailView, ArticleUpdateView, ArticleDeleteView
from django.views.decorators.cache import cache_page


urlpatterns = [
    path('create/', ArticleCreateView.as_view(), name='create'),
    path('', cache_page(60*60)(BlogListView.as_view()), name='list'),
    path('read/<slug:slug>/', ArticleDetailView.as_view(), name='view'),
    path('edit/<slug:slug>/', ArticleUpdateView.as_view(), name='update'),
    path('delete/<slug:slug>/', ArticleDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from main.views import page_not_found

urlpatterns = (([
                    path('admin/', admin.site.urls),
                    path('', include('main.urls')),
                    path('blog/', include('blog.urls')),
                    path('users/', include('users.urls')),
                ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
               + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

handler404 = page_not_found

# admin.site.site_header = 'Admin Panel'
# admin.site.index_title = 'MailMate'

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from .views import LoginUser, RegisterUser, ProfileUser, UserPasswordChange, activation_sent_view, activate_account, \
    user_list

app_name = 'users'

urlpatterns = [
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    # for changing password
    path('password-change/', UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"),
         name='password_change_done'),

    # for generating a link to reset password
    path('password-reset/',
         PasswordResetView.as_view(
             template_name="users/password_reset_form.html",
             email_template_name="users/password_reset_email.html",
             success_url=reverse_lazy("users:password_reset_done")
         ),
         name='password_reset'),

    path('password-reset/done/',
         PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
         name='password_reset_done'),

    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html",
                                          success_url=reverse_lazy("users:password_reset_complete")),
         name='password_reset_confirm'),
    path('password-reset/complete/',
         PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"),
         name='password_reset_complete'),

    path('register/', RegisterUser.as_view(), name='register'),
    path('activation-sent/', activation_sent_view, name='activation_sent'),
    path('activate/<str:activation_token>/', activate_account, name='activate'),
    path('profile/', ProfileUser.as_view(), name='profile'),

    path('', user_list, name='user_list'),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Article(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'draft', 'Draft'
        PUBLISHED = 'published', 'Published'

    title = models.CharField(max_length=100, verbose_name='Title')
    slug = models.CharField(max_length=100, unique=True, db_index=True)
    content = models.TextField(blank=True, null=True, db_index=True)
    image = models.ImageField(upload_to='images/blog/', blank=True, null=True, verbose_name='Image Path')
    time_created = models.DateTimeField(auto_now_add=True)
    publication = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.PUBLISHED,
    )
    views_count = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        # Checks if there is an image
        if self.image:
            # Deletes image
            self.image.delete()
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'article'
        verbose_name_plural = 'articles'

    def get_absolute_url(self):
        return reverse('view', kwargs={'slug': self.slug})

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model


class Client(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    email = models.EmailField()
    full_name = models.CharField(max_length=255, verbose_name='Full Name')
    comment = models.TextField(null=True, blank=True)
    tag = models.CharField(max_length=30, null=True, blank=True)

    def __str__(self):
        return f'{self.tag}'

    class Meta:
        verbose_name = 'client'
        verbose_name_plural = 'clients'
        ordering = ['tag']
        unique_together = (('owner', 'email'),)


class MailingMessage(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    name = models.CharField(max_length=100, null=True, blank=True)
    subject = models.CharField(max_length=255)
    body = models.TextField(verbose_name='Content')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'template'
        verbose_name_plural = 'templates'
        ordering = ['pk']


class MailCampaign(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    campaign_name = models.CharField(max_length=100)
    send_time = models.DateTimeField(blank=True, null=True)

    FREQUENCY_CHOICES = [
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('monthly', 'Monthly'),
    ]
    frequency = models.CharField(max_length=10, blank=True, null=True, choices=FREQUENCY_CHOICES)

    STATUS_CHOICES = [
        ('completed', 'Completed'),
        ('created', 'Created'),
        ('launched', 'Launched'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='created')
    template = models.ForeignKey(MailingMessage, on_delete=models.CASCADE)
    client_tag = models.ForeignKey(Client, blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        # Django creates method get_<field_name>_display() when choices are used
        return f'{self.campaign_name} - {self.client_tag} - {self.get_status_display()}'

    def formatted_send_time(self):
        # Returns 'not set' if field send_time is not set
        return timezone.localtime(self.send_time).strftime("%d.%m.%Y - %H:%M") if self.send_time else "not set"

    def save(self, *args, **kwargs):
        if self.frequency is None:
            self.frequency = 'not set'
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'mail campaign'
        verbose_name_plural = 'mail campaigns'
        ordering = ['pk']


class MailingLog(models.Model):
    owner = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    mailing = models.ForeignKey(MailCampaign, on_delete=models.CASCADE, related_name='mailing')
    campaign_name = models.CharField(max_length=100)
    attempt_datetime = models.DateTimeField()
    completion_datetime = models.DateTimeField(null=True, blank=True)

    STATUS_CHOICES = [
        ('launched', 'Launched'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES)
    server_response = models.TextField(null=True, blank=True)

    def __str__(self):
        return f'{self.campaign_name} - {self.attempt_datetime} - {self.status}'

    class Meta:
        verbose_name = 'mailing log'
        verbose_name_plural = 'mailing logs'
        ordering = ['attempt_datetime']

templates/base.html
{% load static %}

<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">

    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">

    <link rel="icon" href="{% static 'images/letter.png' %}">
    <title>{{ page_title|default:'Mail Mate' }}</title>
</head>

<body>

<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
                    <use xlink:href="#bootstrap"/>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{% url 'home' %}" class="nav-link px-2 text-white">Home</a></li>
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="nav-link px-2 text-white dropdown-toggle" id="featuresDropdown1" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">My MailMate</a>
                    <ul class="dropdown-menu" aria-labelledby="featuresDropdown1">
                        <li><a class="dropdown-item" href="{% url 'campaign_list' %}">Campaigns</a></li>
                        <li><a class="dropdown-item" href="{% url 'template_list' %}">Templates</a></li>
                        <li><a class="dropdown-item" href="{% url 'client_list' %}">Clients</a></li>
                        <li><a class="dropdown-item" href="{% url 'mailing_logs' %}">Mailing Logs</a></li>
                    </ul>
                </li>
                {% endif %}
                <li><a href="/blog/" class="nav-link px-2 text-white">Blog</a></li>
            </ul>

            <div class="position-absolute end-0 pe-5 d-flex">
                {% if user.is_authenticated %}
                <button type="button" class="btn btn-outline-light me-2">
                    <a href="{% url 'users:profile' %}" style="color: inherit; text-decoration: none;">
                        {{ user.username|default:'guest' }}</a>
                </button>

                <button type="button" class="btn btn-warning me-2">
                    <a href="{% url 'users:logout' %}"
                       style="color: inherit; text-decoration: none;">Logout</a>
                </button>
                {% else %}
                <button type="button" class="btn btn-outline-light me-2">
                    <a href="{% url 'users:login' %}"
                       style="color: inherit; text-decoration: none;">Login</a>
                </button>
                <button type="button" class="btn btn-warning me-2">
                    <a href="{% url 'users:register' %}"
                       style="color: inherit; text-decoration: none;">Sign-up</a>
                </button>
                {% endif %}
                {% if perms.blog.add_article %}
                <div class="dropdown ms-auto">
                    <a href="#" class="nav-link px-2 text-white dropdown-toggle" id="featuresDropdown3" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Admin</a>
                    <ul class="dropdown-menu" aria-labelledby="featuresDropdown3">
                        <a class="dropdown-item" href="{% url 'create' %}">Add a Post</a>
                        {% endif %}
                         {% if user.is_staff %}
                        <a class="dropdown-item" href="/users/">Users List</a>
                        <a class="dropdown-item" href="/admin/">Admin Panel</a>
                    </ul>
                </div>
                {% endif %}
            </div>

        </div>
    </div>
</header>

{% block content %}
{% endblock %}


<!-- FOOTER -->
<footer class="footer mt-auto py-3 bg-dark text-white fixed-bottom">
    <div class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>&copy; 2023 - {% now 'Y' %} &middot; Mail Mate - Mailing List Management Service &middot; <a
                href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
    </div>
</footer>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>

</body>
</html>